import type { AppearanceOption, EquipmentItem } from './types';

// ── APPEARANCE ───────────────────────────────────────────────────
export const appearanceOptions: AppearanceOption[] = [
  // Skin Tones
  { id: 'fair', slot: 'skinTone', name: 'Fair Ivory', value: '#fde68a', rarity: 'common' },
  { id: 'sand', slot: 'skinTone', name: 'Desert Sand', value: '#ecd1ad', rarity: 'common' },
  { id: 'amber', slot: 'skinTone', name: 'Warm Amber', value: '#f6c28b', rarity: 'common' },
  { id: 'honey', slot: 'skinTone', name: 'Golden Honey', value: '#d9a066', rarity: 'common' },
  { id: 'olive', slot: 'skinTone', name: 'Olive Bronze', value: '#bf8654', rarity: 'common' },
  { id: 'walnut', slot: 'skinTone', name: 'Rich Walnut', value: '#9a5e35', rarity: 'common' },
  { id: 'cocoa', slot: 'skinTone', name: 'Deep Cocoa', value: '#5c3319', rarity: 'common' },
  { id: 'espresso', slot: 'skinTone', name: 'Midnight Espresso', value: '#381e0b', rarity: 'common' },

  // Hairstyles
  { id: 'short', slot: 'hairStyle', name: 'Classic Taper', value: 'short', rarity: 'common' },
  { id: 'curls', slot: 'hairStyle', name: 'Bouncy Curls', value: 'curls', rarity: 'common' },
  { id: 'waves', slot: 'hairStyle', name: 'Flowing Waves', value: 'waves', rarity: 'common' },
  { id: 'braids', slot: 'hairStyle', name: 'Box Braids & Gold Beads', value: 'braids', rarity: 'uncommon' },
  { id: 'coils', slot: 'hairStyle', name: 'Textured Afro Coils', value: 'coils', rarity: 'common' },
  { id: 'afro', slot: 'hairStyle', name: 'Halo Afro', value: 'afro', rarity: 'uncommon' },
  { id: 'ponytail', slot: 'hairStyle', name: 'High Explorer Ponytail', value: 'ponytail', rarity: 'common' },
  { id: 'fade', slot: 'hairStyle', name: 'Fresh Curly Fade', value: 'fade', rarity: 'uncommon' },
  { id: 'bald', slot: 'hairStyle', name: 'Clean Shaved', value: 'bald', rarity: 'common' },

  // Faces & Expressions
  { id: 'neutral', slot: 'face', name: 'Calm & Steady', value: 'neutral', rarity: 'common' },
  { id: 'smile', slot: 'face', name: 'Warm Gentle Smile', value: 'smile', rarity: 'common' },
  { id: 'grin', slot: 'face', name: 'Joyful Grin', value: 'grin', rarity: 'common' },
  { id: 'calm', slot: 'face', name: 'Peaceful Serenity', value: 'calm', rarity: 'common' },
  { id: 'wonder', slot: 'face', name: 'Curious Wonder', value: 'wonder', rarity: 'common' },
  { id: 'thinking', slot: 'face', name: 'Contemplative', value: 'thinking', rarity: 'uncommon' },
  { id: 'celebrating', slot: 'face', name: 'Sparkle Celebration', value: 'celebrating', rarity: 'rare' },
  { id: 'victory', slot: 'face', name: 'Confident Victory', value: 'victory', rarity: 'rare' },
];

// ── EQUIPMENT & SHOP ITEMS ────────────────────────────────────────
export const equipmentItems: EquipmentItem[] = [
  // ── HEADWEAR ──
  {
    id: 'starter-cap',
    slot: 'headwear',
    name: 'Traveler’s Cap',
    description: 'Classic durable adventure cap with emblem.',
    emoji: '🧢',
    rarity: 'common',
    priceCoins: 0,
    unlockRequirement: [{ type: 'always' }],
  },
  {
    id: 'scouts-hood',
    slot: 'headwear',
    name: 'Scout’s Forest Hood',
    description: 'Lightweight cowl for tracking trails in Galilee.',
    emoji: '🎽',
    rarity: 'uncommon',
    priceCoins: 120,
    unlockRequirement: [{ type: 'level', minLevel: 3 }],
  },
  {
    id: 'kingdom-crown',
    slot: 'headwear',
    name: 'Crown of Israel',
    description: 'Golden crown commemorating the Davidic kingdom.',
    emoji: '👑',
    rarity: 'epic',
    priceCoins: 450,
    priceGems: 5,
    unlockRequirement: [{ type: 'region-complete', regionId: 'jerusalem', minQuestsCompleted: 1 }],
  },
  {
    id: 'guardian-halo',
    slot: 'headwear',
    name: 'Guardian’s Halo',
    description: 'Luminous celestial ring forged from heavenly light.',
    emoji: '😇',
    rarity: 'legendary',
    priceCoins: 800,
    priceGems: 15,
    unlockRequirement: [{ type: 'level', minLevel: 20 }],
  },

  // ── CLOTHING ──
  {
    id: 'starter-tunic',
    slot: 'clothing',
    name: 'Traveler’s Tunic',
    description: 'Comfortable royal blue tunic woven for Bible explorers.',
    emoji: '👕',
    rarity: 'common',
    priceCoins: 0,
    unlockRequirement: [{ type: 'always' }],
  },
  {
    id: 'explorer-hoodie',
    slot: 'clothing',
    name: 'Emerald Explorer Hoodie',
    description: 'Modern zip hoodie with reinforced elbow patches.',
    emoji: '🧥',
    rarity: 'uncommon',
    priceCoins: 200,
    unlockRequirement: [{ type: 'level', minLevel: 4 }],
  },
  {
    id: 'wilderness-cloak',
    slot: 'clothing',
    name: 'Wilderness Camel Cloak',
    description: 'Weatherproof desert cloak reminiscent of Elijah and John.',
    emoji: '🧣',
    rarity: 'rare',
    priceCoins: 350,
    unlockRequirement: [{ type: 'region-complete', regionId: 'wilderness', minQuestsCompleted: 3 }],
  },
  {
    id: 'silver-robe',
    slot: 'clothing',
    name: 'Silver Kingdom Robe',
    description: 'Clean ceremonial linen robe with sapphire sash.',
    emoji: '🥋',
    rarity: 'epic',
    priceCoins: 500,
    priceGems: 5,
    unlockRequirement: [{ type: 'level', minLevel: 10 }],
  },
  {
    id: 'golden-cloak',
    slot: 'clothing',
    name: 'Golden Guardian Cloak',
    description: 'Radiant golden mantle given to steadfast champions.',
    emoji: '✨',
    rarity: 'legendary',
    priceCoins: 1000,
    priceGems: 20,
    unlockRequirement: [{ type: 'level', minLevel: 30 }],
  },
  {
    id: 'denim-jacket',
    slot: 'clothing',
    name: 'Lion’s Den Denim Jacket',
    description: 'Streetwear-style denim jacket featuring the Lion crest.',
    emoji: '🧥',
    rarity: 'rare',
    priceCoins: 300,
    unlockRequirement: [{ type: 'level', minLevel: 7 }],
  },
  {
    id: 'scripture-tee',
    slot: 'clothing',
    name: 'Scripture Graphic Tee',
    description: 'Breathable cotton tee stamped with the Golden Lantern.',
    emoji: '👕',
    rarity: 'common',
    priceCoins: 80,
    unlockRequirement: [{ type: 'always' }],
  },

  // ── SHOES ──
  {
    id: 'starter-sandals',
    slot: 'shoes',
    name: 'Simple Sandals',
    description: 'Leather strapped sandals built for long dusty walks.',
    emoji: '🩴',
    rarity: 'common',
    priceCoins: 0,
    unlockRequirement: [{ type: 'always' }],
  },
  {
    id: 'adventurers-boots',
    slot: 'shoes',
    name: 'Adventurer’s Trail Boots',
    description: 'Rugged leather boots with brass buckles.',
    emoji: '🥾',
    rarity: 'uncommon',
    priceCoins: 150,
    unlockRequirement: [{ type: 'level', minLevel: 3 }],
  },
  {
    id: 'runners-sandals',
    slot: 'shoes',
    name: 'Winged Peace Sandals',
    description: 'Gospel of peace footwear with golden winglets.',
    emoji: '👟',
    rarity: 'rare',
    priceCoins: 320,
    unlockRequirement: [{ type: 'region-complete', regionId: 'gospels', minQuestsCompleted: 1 }],
  },
  {
    id: 'high-top-sneakers',
    slot: 'shoes',
    name: 'Lion Pro High-Tops',
    description: 'Cushioned modern court sneakers with amber accents.',
    emoji: '👟',
    rarity: 'rare',
    priceCoins: 280,
    unlockRequirement: [{ type: 'level', minLevel: 6 }],
  },

  // ── ACCESSORIES ──
  {
    id: 'garden-leaf-pin',
    slot: 'accessory',
    name: 'Garden Leaf Pin',
    description: 'Handcrafted emerald leaf pin from the Garden of Eden.',
    emoji: '🍃',
    rarity: 'uncommon',
    priceCoins: 90,
    unlockRequirement: [{ type: 'quest-complete', questId: 'quest-eden-1' }],
  },
  {
    id: 'shepherd-sling',
    slot: 'accessory',
    name: 'Shepherd’s Sling',
    description: 'Woven sling carrying smooth river stones.',
    emoji: '🪨',
    rarity: 'rare',
    priceCoins: 220,
    unlockRequirement: [{ type: 'quest-complete', questId: 'quest-jerusalem-1' }],
  },
  {
    id: 'cross-pendant',
    slot: 'accessory',
    name: 'Golden Cross Pendant',
    description: 'Polished gold cross on a delicate link chain.',
    emoji: '✝️',
    rarity: 'epic',
    priceCoins: 380,
    priceGems: 4,
    unlockRequirement: [{ type: 'region-complete', regionId: 'jerusalem', minQuestsCompleted: 3 }],
  },
  {
    id: 'scholar-glasses',
    slot: 'accessory',
    name: 'Scholar’s Wireframe Glasses',
    description: 'Gold-rimmed round spectacles for close scripture study.',
    emoji: '👓',
    rarity: 'uncommon',
    priceCoins: 140,
    unlockRequirement: [{ type: 'level', minLevel: 4 }],
  },
  {
    id: 'scripture-band',
    slot: 'accessory',
    name: 'Woven Scripture Wristband',
    description: 'Braided leather wristband with engraved brass plaque.',
    emoji: '🎗️',
    rarity: 'common',
    priceCoins: 60,
    unlockRequirement: [{ type: 'always' }],
  },

  // ── BACKPACKS ──
  {
    id: 'starter-satchel',
    slot: 'backpack',
    name: 'Traveler’s Side Satchel',
    description: 'Sturdy crossbody canvas bag for field notebooks.',
    emoji: '👜',
    rarity: 'common',
    priceCoins: 0,
    unlockRequirement: [{ type: 'always' }],
  },
  {
    id: 'explorer-backpack',
    slot: 'backpack',
    name: 'Mountain Explorer Pack',
    description: 'Multi-pocket hiking pack with bedroll straps.',
    emoji: '🎒',
    rarity: 'rare',
    priceCoins: 300,
    unlockRequirement: [{ type: 'level', minLevel: 5 }],
  },
  {
    id: 'scrolls-backpack',
    slot: 'backpack',
    name: 'Scribe’s Scripture Scrolls Pack',
    description: 'Hard leather cylindrical case holding ancient scrolls.',
    emoji: '📜',
    rarity: 'epic',
    priceCoins: 480,
    priceGems: 6,
    unlockRequirement: [{ type: 'level', minLevel: 12 }],
  },
  {
    id: 'celestial-wings-pack',
    slot: 'backpack',
    name: 'Celestial Light Wing Pack',
    description: 'Iridescent glowing wings that flutter with faith.',
    emoji: '🪽',
    rarity: 'legendary',
    priceCoins: 900,
    priceGems: 18,
    unlockRequirement: [{ type: 'level', minLevel: 25 }],
  },

  // ── LANTERNS ──
  {
    id: 'starter-lantern',
    slot: 'lantern',
    name: 'Apprentice Bronze Lantern',
    description: 'Reliable hand-welded bronze lantern with a warm candle.',
    emoji: '🏮',
    rarity: 'common',
    priceCoins: 0,
    unlockRequirement: [{ type: 'always' }],
  },
  {
    id: 'explorer-lantern',
    slot: 'lantern',
    name: 'Brass Compass Lantern',
    description: 'Integrated directional beacon that illuminates every trail.',
    emoji: '🧭',
    rarity: 'uncommon',
    priceCoins: 180,
    unlockRequirement: [{ type: 'level', minLevel: 5 }],
  },
  {
    id: 'golden-lantern',
    slot: 'lantern',
    name: 'Golden Beacon of Zion',
    description: 'Pure gold filigree lantern that casts a sunburst glow.',
    emoji: '✨',
    rarity: 'epic',
    priceCoins: 500,
    priceGems: 8,
    unlockRequirement: [{ type: 'level', minLevel: 10 }],
  },
  {
    id: 'scripture-lantern',
    slot: 'lantern',
    name: 'Living Word Scripture Luminary',
    description: 'Inscribed with verse passages that project onto the ground.',
    emoji: '📖',
    rarity: 'epic',
    priceCoins: 650,
    priceGems: 10,
    unlockRequirement: [{ type: 'region-complete', regionId: 'jerusalem', minQuestsCompleted: 3 }],
  },
  {
    id: 'celestial-fire-lantern',
    slot: 'lantern',
    name: 'Celestial Blue Flame Lantern',
    description: 'Never-ending divine blue fire that wards off darkness.',
    emoji: '🔥',
    rarity: 'legendary',
    priceCoins: 1200,
    priceGems: 25,
    unlockRequirement: [{ type: 'level', minLevel: 30 }],
  },

  // ── PETS & COMPANIONS ──
  {
    id: 'lion-cub-pet',
    slot: 'pet',
    name: 'Brave Little Lion Cub',
    description: 'Loyal and playful cub inspired by the Lion of Judah.',
    emoji: '🦁',
    rarity: 'rare',
    priceCoins: 400,
    priceGems: 5,
    unlockRequirement: [{ type: 'level', minLevel: 5 }],
    isCompanion: true,
  },
  {
    id: 'lost-sheep-companion',
    slot: 'pet',
    name: 'Little Lost Lamb',
    description: 'Gentle, joyful lamb rescued from the wilderness.',
    emoji: '🐑',
    rarity: 'uncommon',
    priceCoins: 250,
    unlockRequirement: [{ type: 'quest-complete', questId: 'quest-gospels-1' }],
    isCompanion: true,
  },
  {
    id: 'peace-dove-pet',
    slot: 'pet',
    name: 'Olive Peace Dove',
    description: 'Graceful white dove carrying an emerald olive sprig.',
    emoji: '🕊️',
    rarity: 'rare',
    priceCoins: 350,
    priceGems: 4,
    unlockRequirement: [{ type: 'level', minLevel: 8 }],
    isCompanion: true,
  },
  {
    id: 'desert-eagle-pet',
    slot: 'pet',
    name: 'Soaring Mount Eagle',
    description: 'Mighty eagle that mounts up with wings like faith.',
    emoji: '🦅',
    rarity: 'legendary',
    priceCoins: 850,
    priceGems: 15,
    unlockRequirement: [{ type: 'level', minLevel: 18 }],
    isCompanion: true,
  },

  // ── EMOTES ──
  {
    id: 'emote-wave',
    slot: 'emote',
    name: 'Friendly Wave',
    description: 'Wave hello to your friends and church club teammates.',
    emoji: '👋',
    rarity: 'common',
    priceCoins: 50,
    unlockRequirement: [{ type: 'always' }],
  },
  {
    id: 'emote-celebrate',
    slot: 'emote',
    name: 'Confetti Jump',
    description: 'Celebrate a big story milestone or quiz victory!',
    emoji: '🎉',
    rarity: 'uncommon',
    priceCoins: 120,
    unlockRequirement: [{ type: 'level', minLevel: 3 }],
  },
  {
    id: 'emote-victory',
    slot: 'emote',
    name: 'Hero’s Triumph Pose',
    description: 'Hold your lantern high with confidence.',
    emoji: '🏆',
    rarity: 'rare',
    priceCoins: 250,
    unlockRequirement: [{ type: 'level', minLevel: 6 }],
  },
  {
    id: 'emote-prayer',
    slot: 'emote',
    name: 'Grateful Praise & Prayer',
    description: 'Bow your head with folded hands in thanksgiving.',
    emoji: '🙏',
    rarity: 'rare',
    priceCoins: 200,
    unlockRequirement: [{ type: 'always' }],
  },

  // ── SPECIAL ──
  {
    id: 'manna-basket-charm',
    slot: 'special',
    name: 'Manna Basket Charm',
    description: 'A miraculous keepsake reminding us of daily bread.',
    emoji: '🍞',
    rarity: 'uncommon',
    priceCoins: 100,
    unlockRequirement: [{ type: 'quest-complete', questId: 'quest-wilderness-1' }],
  },
  {
    id: 'tomb-light-halo',
    slot: 'special',
    name: 'Resurrection Sunrise Aura',
    description: 'Gleaming sunbeams representing the empty tomb.',
    emoji: '🌅',
    rarity: 'legendary',
    priceCoins: 950,
    priceGems: 20,
    unlockRequirement: [{ type: 'quest-complete', questId: 'quest-gospels-1' }],
  },
  {
    id: 'flame-of-faith-badge',
    slot: 'special',
    name: 'Flame of Pentecost Badge',
    description: 'Warm glowing crest celebrating the early church.',
    emoji: '🔥',
    rarity: 'rare',
    priceCoins: 300,
    unlockRequirement: [{ type: 'quest-complete', questId: 'quest-early-church-1' }],
  },
];

export const EQUIPMENT_SLOTS: { id: EquipmentItem['slot']; label: string; icon: string }[] = [
  { id: 'headwear', label: 'Headwear', icon: '🧢' },
  { id: 'clothing', label: 'Outfits & Tops', icon: '👕' },
  { id: 'shoes', label: 'Shoes & Boots', icon: '🥾' },
  { id: 'accessory', label: 'Accessories', icon: '✝️' },
  { id: 'backpack', label: 'Backpacks', icon: '🎒' },
  { id: 'lantern', label: 'Lanterns', icon: '🏮' },
  { id: 'pet', label: 'Pets & Companions', icon: '🦁' },
  { id: 'emote', label: 'Emotes & Poses', icon: '🎉' },
  { id: 'special', label: 'Special Artifacts', icon: '✨' },
];

export function getAppearanceOptionsForSlot(slot: AppearanceOption['slot']): AppearanceOption[] {
  return appearanceOptions.filter((option) => option.slot === slot);
}

export function getAppearanceOption(slot: AppearanceOption['slot'], id: string): AppearanceOption | undefined {
  return appearanceOptions.find((option) => option.slot === slot && option.id === id);
}

export function getItemsForSlot(slot: EquipmentItem['slot']): EquipmentItem[] {
  return equipmentItems.filter((item) => item.slot === slot);
}

export function getItem(itemId: string): EquipmentItem | undefined {
  return equipmentItems.find((item) => item.id === itemId);
}

export function getStarterItemForSlot(slot: EquipmentItem['slot']): EquipmentItem | undefined {
  return getItemsForSlot(slot).find((item) => item.unlockRequirement.some((req) => req.type === 'always'));
}

