'use client';

import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Page='overview'|'classes'|'assignments'|'messages'|'safety';
type Student={id:number;name:string;age:number;progress:number;needsHelp:boolean;parent:string};
type Classroom={id:number;name:string;ageBand:string;code:string;students:Student[]};
type Assignment={id:number;classId:number;title:string;due:string;completed:number};
const starterClasses:Classroom[]=[{id:1,name:'Wednesday Explorers',ageBand:'Ages 8–11',code:'LION-482',students:[{id:1,name:'Amara A.',age:9,progress:78,needsHelp:false,parent:'Jordan A.'},{id:2,name:'Mia K.',age:10,progress:52,needsHelp:true,parent:'Chidi K.'},{id:3,name:'Noah B.',age:8,progress:91,needsHelp:false,parent:'Sarah B.'}]},{id:2,name:'Friday Teen Circle',ageBand:'Ages 13–16',code:'LAMP-731',students:[{id:4,name:'Tobi A.',age:14,progress:64,needsHelp:false,parent:'Jordan A.'},{id:5,name:'Jay O.',age:15,progress:36,needsHelp:true,parent:'Helen O.'}]}];
const lessons=['David chooses courage','Build Psalm 119:105','Samuel listens','A kind choice at lunch','What did Ruth notice?'];

export default function TeacherDashboardPage(){
 const [page,setPage]=useState<Page>('overview'); const [classes,setClasses]=useState<Classroom[]>(starterClasses); const [activeClass,setActiveClass]=useState(1); const [assignments,setAssignments]=useState<Assignment[]>([{id:1,classId:1,title:'David chooses courage',due:'Friday',completed:2},{id:2,classId:2,title:'Build Psalm 119:105',due:'Sunday',completed:1}]); const [notice,setNotice]=useState(''); const [newClass,setNewClass]=useState(''); const [ageBand,setAgeBand]=useState('Ages 8–11'); const [studentName,setStudentName]=useState(''); const [lesson,setLesson]=useState(lessons[0]); const [due,setDue]=useState('Friday'); const [message,setMessage]=useState(''); const [selectedStudent,setSelectedStudent]=useState(1); const [sentMessages,setSentMessages]=useState<Array<{studentId:number;body:string}>>([]); const [reviewed,setReviewed]=useState<number[]>([]); const [hydrated,setHydrated]=useState(false);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem('lanternLionTeacherClasses')||'null');const work=JSON.parse(localStorage.getItem('lanternLionTeacherAssignments')||'null');if(Array.isArray(saved)&&saved.length)setClasses(saved);if(Array.isArray(work))setAssignments(work);}catch{}setHydrated(true);},0);return()=>clearTimeout(timer)},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3200);return()=>clearTimeout(timer)},[notice]);
 const classroom=classes.find(item=>item.id===activeClass)||classes[0]; const students=classes.flatMap(item=>item.students); const helpStudents=students.filter(item=>item.needsHelp&&!reviewed.includes(item.id)); const average=Math.round(students.reduce((sum,item)=>sum+item.progress,0)/students.length); const activeAssignments=assignments.filter(item=>item.classId===activeClass);
 function saveClasses(next:Classroom[]){setClasses(next);localStorage.setItem('lanternLionTeacherClasses',JSON.stringify(next));}
 function createClass(){if(!newClass.trim()){setNotice('Add a class name first.');return;}const nextClass:Classroom={id:Date.now(),name:newClass.trim(),ageBand,code:`LIGHT-${Math.floor(100+Math.random()*900)}`,students:[]};const next=[...classes,nextClass];saveClasses(next);setActiveClass(nextClass.id);setNewClass('');setNotice(`${nextClass.name} is ready. Share its code only with approved families.`);}
 function addStudent(){if(!studentName.trim())return;const next=classes.map(item=>item.id===activeClass?{...item,students:[...item.students,{id:Date.now(),name:studentName.trim(),age:item.ageBand.includes('13')?14:9,progress:0,needsHelp:false,parent:'Parent invitation pending'}]}:item);saveClasses(next);setStudentName('');setNotice(`${studentName.trim()} was added. Their parent must approve the profile before learning begins.`);}
 function regenerateCode(){const code=`LIGHT-${Math.floor(100+Math.random()*900)}`;saveClasses(classes.map(item=>item.id===activeClass?{...item,code}:item));setNotice('A new join code is ready. The old code no longer works in this demo.');}
 function assign(){const existing=assignments.find(item=>item.classId===activeClass&&item.title===lesson);let next:Assignment[];if(existing)next=assignments.map(item=>item.id===existing.id?{...item,due}:item);else next=[...assignments,{id:Date.now(),classId:activeClass,title:lesson,due,completed:0}];setAssignments(next);localStorage.setItem('lanternLionTeacherAssignments',JSON.stringify(next));setNotice(existing?'The due date was updated.':`${lesson} was assigned to ${classroom.name}.`);}
 const nav:Array<[Page,string,string]>=[['overview','O','Overview'],['classes','C','Classes'],['assignments','A','Assignments'],['messages','M','Parent messages'],['safety','S','Safety']];
 if(!hydrated)return <main className="dashboard-loading"><span></span><p>Opening the teacher space…</p></main>;
 return <main className="teacher-dashboard"><aside className="teacher-sidebar"><Link href="/" className="teacher-brand"><Image src="/lantern-lion-logo.png" alt="" width={58} height={58}/><span><strong>Lantern &amp; Lion</strong><small>Teacher space</small></span></Link><nav aria-label="Teacher dashboard">{nav.map(([id,mark,label])=><button key={id} className={page===id?'active':''} aria-pressed={page===id} onClick={()=>setPage(id)}><span>{mark}</span>{label}{id==='safety'&&helpStudents.length>0?<b>{helpStudents.length}</b>:null}</button>)}</nav><div><Link href="/learn?activity=david-chooses-courage">Preview an activity</Link><Link href="/teacher-access">Sign out of demo</Link></div></aside><section className="teacher-main"><header className="teacher-topbar"><div><span>Teacher workspace</span><strong>Grace Okafor</strong></div><label>Current class<select value={activeClass} onChange={e=>setActiveClass(Number(e.target.value))}>{classes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></header>
 {page==='overview'&&<div className="teacher-content"><div className="teacher-title"><p className="teacher-kicker">Good morning, Grace</p><h1>See the class, not just the scores.</h1><p>Start with the learners who asked for help, then notice the quiet progress happening everywhere else.</p></div><div className="teacher-metrics"><article><span>Students</span><strong>{students.length}</strong><small>Across {classes.length} classes</small></article><article><span>Average progress</span><strong>{average}%</strong><small>This week</small></article><article><span>Active assignments</span><strong>{assignments.length}</strong><small>Nothing overdue</small></article><article className="attention"><span>Needs a look</span><strong>{helpStudents.length}</strong><small>Private help flags</small></article></div><div className="teacher-overview-grid"><section className="teacher-panel"><div className="teacher-panel-head"><div><p className="teacher-kicker">{classroom.name}</p><h2>Learning this week</h2></div><button onClick={()=>setPage('classes')}>Open class</button></div><div className="teacher-roster-mini">{classroom.students.map(student=><article key={student.id}><span>{student.name[0]}</span><div><strong>{student.name}</strong><small>{student.progress}% of this week’s path</small><i><b style={{width:`${student.progress}%`}}/></i></div>{student.needsHelp&&!reviewed.includes(student.id)?<em>Needs help</em>:<b>On path</b>}</article>)}</div></section><aside className="teacher-help-panel"><p className="teacher-kicker">Respond with care</p><h2>{helpStudents.length?`${helpStudents.length} learners asked for help.`:'No new help flags.'}</h2><p>Flags show the activity and attempt pattern. Message the parent if a conversation would help.</p><button onClick={()=>setPage('safety')}>Review help flags</button></aside></div></div>}
 {page==='classes'&&<div className="teacher-content"><div className="teacher-title"><p className="teacher-kicker">Classes and groups</p><h1>Keep every learning circle clear.</h1><p>Join codes connect approved families. Children never create public profiles or search for a classroom.</p></div><div className="teacher-class-tabs">{classes.map(item=><button key={item.id} className={activeClass===item.id?'active':''} onClick={()=>setActiveClass(item.id)}><strong>{item.name}</strong><small>{item.ageBand} · {item.students.length} students</small></button>)}</div><section className="teacher-panel teacher-class-detail"><div className="teacher-panel-head"><div><p className="teacher-kicker">{classroom.ageBand}</p><h2>{classroom.name}</h2></div><div className="join-code"><span>Family join code</span><strong>{classroom.code}</strong><button onClick={regenerateCode}>Make a new code</button></div></div><div className="teacher-table">{classroom.students.map(student=><article key={student.id}><span>{student.name[0]}</span><div><strong>{student.name}</strong><small>Age {student.age} · Parent: {student.parent}</small></div><b>{student.progress}%</b><button onClick={()=>setNotice(`A parent-safe progress note for ${student.name} is ready to review.`)}>View learner</button></article>)}{!classroom.students.length&&<p>No students yet. Add the first approved learner below.</p>}</div><div className="teacher-add-student"><label>Student’s display name<input value={studentName} onChange={e=>setStudentName(e.target.value)} placeholder="For example, Ada O."/></label><button onClick={addStudent}>Add pending student</button></div></section><section className="teacher-create-class"><div><p className="teacher-kicker">Create another class</p><h2>A new learning circle</h2></div><label>Class name<input value={newClass} onChange={e=>setNewClass(e.target.value)} placeholder="Sunday Juniors"/></label><label>Age group<select value={ageBand} onChange={e=>setAgeBand(e.target.value)}><option>Ages 5–7</option><option>Ages 8–11</option><option>Ages 12–14</option><option>Ages 13–16</option></select></label><button onClick={createClass}>Create class</button></section></div>}
 {page==='assignments'&&<div className="teacher-content"><div className="teacher-title"><p className="teacher-kicker">Assignments</p><h1>Choose one useful next step.</h1><p>Assigned work appears first, but students can still explore the rest of their age-appropriate library.</p></div><section className="teacher-assignment-builder"><div><label>Class<select value={activeClass} onChange={e=>setActiveClass(Number(e.target.value))}>{classes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Activity<select value={lesson} onChange={e=>setLesson(e.target.value)}>{lessons.map(item=><option key={item}>{item}</option>)}</select></label><label>Finish by<select value={due} onChange={e=>setDue(e.target.value)}><option>Friday</option><option>Sunday</option><option>Next Wednesday</option><option>No due date</option></select></label><button onClick={assign}>Assign to class</button></div><aside><p className="teacher-kicker">Current class work</p>{activeAssignments.length?activeAssignments.map(item=><article key={item.id}><span>A</span><div><strong>{item.title}</strong><small>{item.completed} of {classroom.students.length} finished · Due {item.due}</small></div><button onClick={()=>{const next=assignments.filter(work=>work.id!==item.id);setAssignments(next);localStorage.setItem('lanternLionTeacherAssignments',JSON.stringify(next));}}>Remove</button></article>):<p>No assignments for this class yet.</p>}</aside></section></div>}
 {page==='messages'&&<div className="teacher-content"><div className="teacher-title"><p className="teacher-kicker">Parent messages</p><h1>Keep adults in the conversation.</h1><p>Teachers message a verified parent account. Children cannot receive or send private messages.</p></div><section className="teacher-message-layout"><aside>{students.slice(0,4).map(student=><button className={selectedStudent===student.id?'active':''} aria-pressed={selectedStudent===student.id} onClick={()=>setSelectedStudent(student.id)} key={student.id}><span>{student.parent[0]}</span><div><strong>{student.parent}</strong><small>Parent of {student.name}</small></div></button>)}</aside><div><header><strong>{students.find(item=>item.id===selectedStudent)?.parent||students[0]?.parent}</strong><small>Parent of {students.find(item=>item.id===selectedStudent)?.name||students[0]?.name}</small></header><div className="teacher-message-list"><p><b>{students.find(item=>item.id===selectedStudent)?.parent||students[0]?.parent}</b>{(students.find(item=>item.id===selectedStudent)?.name||'Your child')} enjoyed the courage story. Is there something we can talk about at home?</p><p className="sent"><b>You</b>Ask what David remembered before he stepped forward. That detail helped today.</p>{sentMessages.filter(item=>item.studentId===selectedStudent).map((item,index)=><p className="sent" key={index}><b>You</b>{item.body}</p>)}</div><form onSubmit={e=>{e.preventDefault();if(!message.trim())return;setSentMessages([...sentMessages,{studentId:selectedStudent,body:message.trim()}]);setNotice('Your message was added to the parent conversation.');setMessage('');}}><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write to the parent, not the child"/><button>Send to parent</button></form></div></section></div>}
 {page==='safety'&&<div className="teacher-content"><div className="teacher-title"><p className="teacher-kicker">Safeguarding</p><h1>Every flag deserves a calm response.</h1><p>Teachers see only students assigned to their classes. Serious concerns should follow your organisation’s safeguarding procedure.</p></div><div className="teacher-safety-banner"><strong>Children cannot message teachers privately.</strong><span>Help flags are visible to the teacher and parent. This demo stores review status only on this device.</span></div><section className="teacher-panel teacher-flags"><div className="teacher-panel-head"><div><p className="teacher-kicker">Open help flags</p><h2>{helpStudents.length} need review</h2></div></div>{helpStudents.map(student=><article key={student.id}><span>!</span><div><strong>{student.name} · {classes.find(item=>item.students.some(member=>member.id===student.id))?.name}</strong><p>Asked for help after two attempts in “Build Psalm 119:105”. No free-text child message was collected.</p><small>Today · Parent: {student.parent}</small></div><button onClick={()=>{setReviewed([...reviewed,student.id]);setNotice(`${student.name}’s flag was marked as reviewed.`)}}>Mark reviewed</button></article>)}{!helpStudents.length&&<div className="teacher-empty"><span>✓</span><strong>Every current flag has been reviewed.</strong></div>}</section></div>}
 {notice&&<div className="teacher-toast" role="status"><span>✓</span><p>{notice}</p><button onClick={()=>setNotice('')}>Close</button></div>}
 </section></main>
}
