// Build the Story — the story bank. Pure content, no game logic. Adding
// story #9, #90, or #900 later is editing this array; nothing about
// `engine.ts` or `page.tsx` needs to change.

import type { StoryDefinition } from './engine';

function events(id: string, texts: string[], hints: Record<number, string> = {}): StoryDefinition['events'] {
  return texts.map((text, i) => ({ id: `${id}-${i}`, text, hint: hints[i] }));
}

export const STORY_BANK: StoryDefinition[] = [
  {
    id: 'noah-flood',
    title: 'Noah and the Flood',
    description: 'God asks Noah to build a huge boat before the rain comes.',
    reference: 'Genesis 6-9',
    ageGroup: 'kids',
    difficulty: 'easy',
    skills: ['sequencing', 'memory', 'bible-knowledge'],
    xpReward: 60,
    image: '/art-module-noah.jpg',
    summary: 'Noah obeyed God even when it seemed strange, and God kept his family and the animals safe.',
    events: events('noah', [
      'God tells Noah to build an ark.',
      'The animals come to the ark two by two.',
      'It rains for forty days and forty nights.',
      'God sends a rainbow as a promise.',
    ]),
  },
  {
    id: 'nativity',
    title: 'The First Christmas',
    description: 'Jesus is born in Bethlehem, just as the prophets said He would be.',
    reference: 'Luke 2:1-20',
    ageGroup: 'kids',
    difficulty: 'easy',
    skills: ['sequencing', 'memory', 'bible-knowledge'],
    xpReward: 60,
    image: '/art-module-nativity.jpg',
    summary: 'God kept His promise to send a Savior, and even the shepherds were invited to celebrate.',
    events: events('nativity', [
      'Mary and Joseph travel to Bethlehem.',
      'Jesus is born and laid in a manger.',
      'An angel tells shepherds the good news.',
      'The shepherds go to see baby Jesus.',
    ]),
  },
  {
    id: 'lost-sheep',
    title: 'The Lost Sheep',
    description: 'A shepherd leaves everything to find the one sheep that wandered off.',
    reference: 'Luke 15:3-7',
    ageGroup: 'kids',
    difficulty: 'easy',
    skills: ['sequencing', 'critical-thinking'],
    xpReward: 60,
    image: '/art-module-lost-sheep.jpg',
    summary: 'God cares about each one of us, just like the shepherd who wouldn’t stop looking for one lost sheep.',
    events: events('lost-sheep', [
      'A shepherd has one hundred sheep.',
      'One sheep wanders away and gets lost.',
      'The shepherd leaves the ninety-nine to search for it.',
      'He finds the sheep and celebrates with joy.',
    ]),
  },
  {
    id: 'david-goliath',
    title: 'David and Goliath',
    description: 'A shepherd boy faces a giant that the whole army was afraid of.',
    reference: '1 Samuel 17',
    ageGroup: 'tweens',
    difficulty: 'medium',
    skills: ['sequencing', 'critical-thinking', 'bible-knowledge'],
    xpReward: 80,
    image: '/art-module-david.jpg',
    summary: 'David trusted God and faced Goliath even when the other soldiers were afraid.',
    events: events(
      'david',
      [
        'Goliath challenges Israel to send a champion.',
        'David arrives at the battlefield with food for his brothers.',
        'David tells King Saul he will fight the giant.',
        'David chooses five smooth stones from the stream.',
        'David confronts Goliath with his sling.',
        'David defeats Goliath with a single stone.',
      ],
      { 3: 'Think about what David needed to gather before he could fight.' },
    ),
  },
  {
    id: 'daniel-lions-den',
    title: 'Daniel in the Lions’ Den',
    description: 'Daniel keeps praying even when a new law says he can’t.',
    reference: 'Daniel 6',
    ageGroup: 'tweens',
    difficulty: 'medium',
    skills: ['sequencing', 'critical-thinking', 'bible-knowledge'],
    xpReward: 80,
    image: '/art-module-daniel.jpg',
    summary: 'Daniel stayed faithful to God no matter the cost, and God protected him.',
    events: events('daniel', [
      'Jealous officials convince the king to outlaw praying to God.',
      'Daniel keeps praying to God three times a day anyway.',
      'The officials catch Daniel praying and report him.',
      'The king reluctantly has Daniel thrown into the lions’ den.',
      'God sends an angel to shut the lions’ mouths.',
      'The king finds Daniel unharmed the next morning.',
    ]),
  },
  {
    id: 'red-sea',
    title: 'Crossing the Red Sea',
    description: 'God rescues Israel from Pharaoh’s army at the edge of the sea.',
    reference: 'Exodus 14',
    ageGroup: 'tweens',
    difficulty: 'hard',
    skills: ['sequencing', 'critical-thinking', 'bible-knowledge'],
    xpReward: 100,
    image: '/art-module-redsea.jpg',
    summary: 'When Israel had nowhere left to run, God made a way where there seemed to be none.',
    events: events('redsea', [
      'Pharaoh finally lets the Israelites leave Egypt.',
      'Pharaoh changes his mind and chases after them with his army.',
      'The Israelites reach the edge of the Red Sea, trapped.',
      'Moses stretches out his hand over the sea.',
      'God drives the sea back with a strong wind, opening a dry path.',
      'The Israelites cross safely on dry ground.',
      'The sea closes over Pharaoh’s pursuing army.',
    ]),
  },
  {
    id: 'esther',
    title: 'Esther Saves Her People',
    description: 'A young queen risks everything to save her people from a deadly plot.',
    reference: 'Esther 2-7',
    ageGroup: 'teens',
    difficulty: 'hard',
    skills: ['sequencing', 'critical-thinking', 'bible-knowledge', 'reading'],
    xpReward: 110,
    image: '/art-module-esther.jpg',
    summary: 'Esther used her position with courage at the exact moment her people needed her most.',
    events: events('esther', [
      'Esther becomes queen of Persia without revealing she is Jewish.',
      'Haman, a powerful official, plots to destroy the Jewish people.',
      'Mordecai urges Esther to speak to the king on her people’s behalf.',
      'Esther fasts and prepares before approaching the king uninvited.',
      'The king extends his scepter and grants Esther an audience.',
      'Esther invites the king and Haman to a banquet.',
      'At the banquet, Esther exposes Haman’s plot to the king.',
      'The king spares the Jewish people and Haman’s plot fails.',
    ]),
  },
  {
    id: 'joseph',
    title: 'Joseph and His Brothers',
    description: 'Betrayed by his own family, Joseph’s story takes a long road toward forgiveness.',
    reference: 'Genesis 37-45',
    ageGroup: 'teens',
    difficulty: 'expert',
    skills: ['sequencing', 'critical-thinking', 'bible-knowledge', 'reading'],
    xpReward: 130,
    image: '/art-module-treasure.jpg',
    summary: 'What Joseph’s brothers meant for harm, God used for good — turning betrayal into rescue for the whole family.',
    events: events(
      'joseph',
      [
        'Jacob gives Joseph a special coat, and his brothers grow jealous.',
        'Joseph’s brothers sell him into slavery in Egypt.',
        'Joseph serves faithfully in Potiphar’s house, then is falsely accused and imprisoned.',
        'Joseph correctly interprets dreams for two fellow prisoners.',
        'Pharaoh has a troubling dream that no one can interpret.',
        'Joseph interprets Pharaoh’s dream, warning of famine after plenty.',
        'Pharaoh puts Joseph in charge of preparing Egypt for the famine.',
        'Joseph’s brothers travel to Egypt to buy grain during the famine.',
        'Joseph reveals his identity and forgives his brothers.',
      ],
      { 2: 'Think about what happened to Joseph right after he arrived in Egypt.', 5: 'Think about whose dream Joseph was asked to explain.' },
    ),
  },
];

export function getStoryDefinition(id: string): StoryDefinition | undefined {
  return STORY_BANK.find((s) => s.id === id);
}
